# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Icarl\Documents\GitHub\onyx-tomi-index-plotter\tomiUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1101, 888)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(
                "c:\\Users\\Icarl\\Documents\\GitHub\\onyx-tomi-index-plotter\\src/main/icons/Icon.ico"
            ),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setStyleSheet(
            "QFrame {\n"
            "    border: 1px solid #212121;\n"
            "    background-color: #fff;\n"
            "}"
        )
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4.addWidget(self.frame)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.homeButton = QtWidgets.QPushButton(self.centralwidget)
        self.homeButton.setObjectName("homeButton")
        self.gridLayout.addWidget(self.homeButton, 0, 0, 1, 1)
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setObjectName("backButton")
        self.gridLayout.addWidget(self.backButton, 0, 1, 1, 1)
        self.forwardButton = QtWidgets.QPushButton(self.centralwidget)
        self.forwardButton.setObjectName("forwardButton")
        self.gridLayout.addWidget(self.forwardButton, 0, 2, 1, 1)
        self.zoomButton = QtWidgets.QPushButton(self.centralwidget)
        self.zoomButton.setObjectName("zoomButton")
        self.gridLayout.addWidget(self.zoomButton, 1, 0, 1, 1)
        self.panButton = QtWidgets.QPushButton(self.centralwidget)
        self.panButton.setObjectName("panButton")
        self.gridLayout.addWidget(self.panButton, 1, 1, 1, 1)
        self.editButton = QtWidgets.QPushButton(self.centralwidget)
        self.editButton.setObjectName("editButton")
        self.gridLayout.addWidget(self.editButton, 1, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.plotTOMIBtn = QtWidgets.QPushButton(self.centralwidget)
        self.plotTOMIBtn.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.plotTOMIBtn.setFont(font)
        self.plotTOMIBtn.setObjectName("plotTOMIBtn")
        self.verticalLayout_4.addWidget(self.plotTOMIBtn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1101, 21))
        self.menubar.setObjectName("menubar")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setAllowedAreas(
            QtCore.Qt.LeftDockWidgetArea | QtCore.Qt.RightDockWidgetArea
        )
        self.dockWidget.setWindowTitle("")
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setMinimumSize(QtCore.QSize(220, 0))
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.importFileBtn = QtWidgets.QToolButton(self.groupBox)
        self.importFileBtn.setObjectName("importFileBtn")
        self.gridLayout_2.addWidget(self.importFileBtn, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.csvFileRadioButton = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.csvFileRadioButton.setFont(font)
        self.csvFileRadioButton.setObjectName("csvFileRadioButton")
        self.fileTOMIBtnGroup = QtWidgets.QButtonGroup(MainWindow)
        self.fileTOMIBtnGroup.setObjectName("fileTOMIBtnGroup")
        self.fileTOMIBtnGroup.addButton(self.csvFileRadioButton)
        self.gridLayout_2.addWidget(
            self.csvFileRadioButton, 4, 0, 1, 2, QtCore.Qt.AlignHCenter
        )
        self.xlsxFileRadioButton = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.xlsxFileRadioButton.setFont(font)
        self.xlsxFileRadioButton.setObjectName("xlsxFileRadioButton")
        self.fileTOMIBtnGroup.addButton(self.xlsxFileRadioButton)
        self.gridLayout_2.addWidget(
            self.xlsxFileRadioButton, 6, 0, 1, 2, QtCore.Qt.AlignHCenter
        )
        self.fileNameInput = QtWidgets.QLineEdit(self.groupBox)
        self.fileNameInput.setObjectName("fileNameInput")
        self.gridLayout_2.addWidget(self.fileNameInput, 1, 0, 1, 1)
        self.txtFileRadioButton = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtFileRadioButton.setFont(font)
        self.txtFileRadioButton.setObjectName("txtFileRadioButton")
        self.fileTOMIBtnGroup.addButton(self.txtFileRadioButton)
        self.gridLayout_2.addWidget(
            self.txtFileRadioButton, 5, 0, 1, 2, QtCore.Qt.AlignHCenter
        )
        self.sheetTabLabel = QtWidgets.QLabel(self.groupBox)
        self.sheetTabLabel.setObjectName("sheetTabLabel")
        self.gridLayout_2.addWidget(self.sheetTabLabel, 7, 0, 1, 2)
        self.sheetPageInput = QtWidgets.QLineEdit(self.groupBox)
        self.sheetPageInput.setStyleSheet(
            "QLineEdit { \n" "    text-align: center; \n" "}"
        )
        self.sheetPageInput.setObjectName("sheetPageInput")
        self.gridLayout_2.addWidget(self.sheetPageInput, 8, 0, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 9, 0, 1, 2)
        self.mesaRotativaInput = QtWidgets.QLineEdit(self.groupBox)
        self.mesaRotativaInput.setObjectName("mesaRotativaInput")
        self.gridLayout_2.addWidget(self.mesaRotativaInput, 10, 0, 1, 2)
        self.plotTOMIBtn_2 = QtWidgets.QPushButton(self.groupBox)
        self.plotTOMIBtn_2.setObjectName("plotTOMIBtn_2")
        self.gridLayout_2.addWidget(self.plotTOMIBtn_2, 11, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 2)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_7.addWidget(self.line)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.formationNameInput = QtWidgets.QLineEdit(self.groupBox_2)
        self.formationNameInput.setObjectName("formationNameInput")
        self.verticalLayout_6.addWidget(self.formationNameInput)
        self.exportDataButton = QtWidgets.QPushButton(self.groupBox_2)
        self.exportDataButton.setObjectName("exportDataButton")
        self.verticalLayout_6.addWidget(self.exportDataButton)
        self.saveButton = QtWidgets.QPushButton(self.groupBox_2)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout_6.addWidget(self.saveButton)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.frame_2 = QtWidgets.QFrame(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_7.addWidget(self.frame_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 4, 0, 1, 3)
        self.plotTitleInput_2 = QtWidgets.QLineEdit(self.tab_2)
        self.plotTitleInput_2.setMinimumSize(QtCore.QSize(0, 20))
        self.plotTitleInput_2.setStyleSheet(
            "QLineEdit {\n"
            "    border: 1px solid #d2d2d2;\n"
            "    background: #fdfdfd;\n"
            "}"
        )
        self.plotTitleInput_2.setObjectName("plotTitleInput_2")
        self.gridLayout_5.addWidget(self.plotTitleInput_2, 1, 0, 1, 3)
        self.krigingInterpolationModel = QtWidgets.QComboBox(self.tab_2)
        self.krigingInterpolationModel.setStyleSheet(
            "QComboBox::item {\n" "    text-align: center;\n" "}"
        )
        self.krigingInterpolationModel.setSizeAdjustPolicy(
            QtWidgets.QComboBox.AdjustToContentsOnFirstShow
        )
        self.krigingInterpolationModel.setIconSize(QtCore.QSize(24, 24))
        self.krigingInterpolationModel.setObjectName("krigingInterpolationModel")
        self.gridLayout_5.addWidget(self.krigingInterpolationModel, 5, 0, 1, 3)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 3)
        self.lineColorComboBox_2 = QtWidgets.QComboBox(self.tab_2)
        self.lineColorComboBox_2.setSizeAdjustPolicy(
            QtWidgets.QComboBox.AdjustToContentsOnFirstShow
        )
        self.lineColorComboBox_2.setObjectName("lineColorComboBox_2")
        self.gridLayout_5.addWidget(self.lineColorComboBox_2, 3, 0, 1, 3)
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 2, 0, 1, 3)
        self.verticalLayout_5.addLayout(self.gridLayout_5)
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5.addWidget(self.frame_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.actionSidebar = QtWidgets.QAction(MainWindow)
        self.actionSidebar.setObjectName("actionSidebar")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.menuView.addAction(self.actionSidebar)
        self.menuView.addAction(self.actionDocumentation)
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.homeButton.setText(_translate("MainWindow", "Reset"))
        self.backButton.setText(_translate("MainWindow", "Voltar"))
        self.forwardButton.setText(_translate("MainWindow", "Avançar"))
        self.zoomButton.setText(_translate("MainWindow", "Zoom"))
        self.panButton.setText(_translate("MainWindow", "Movimentar"))
        self.editButton.setText(_translate("MainWindow", "Editar"))
        self.plotTOMIBtn.setText(_translate("MainWindow", "Plotar"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.groupBox.setTitle(_translate("MainWindow", "Arquivo"))
        self.importFileBtn.setText(_translate("MainWindow", "..."))
        self.label_3.setText(_translate("MainWindow", "Tipo de arquivo:"))
        self.csvFileRadioButton.setText(_translate("MainWindow", ".csv"))
        self.xlsxFileRadioButton.setText(_translate("MainWindow", ".xlsx"))
        self.txtFileRadioButton.setText(_translate("MainWindow", ".txt"))
        self.sheetTabLabel.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-size:12pt;">Aba da Planilha</span></p></body></html>',
            )
        )
        self.label_11.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-size:12pt;">Mesa Rotativa:</span></p></body></html>',
            )
        )
        self.plotTOMIBtn_2.setText(_translate("MainWindow", "Plotar"))
        self.label_2.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">Arquivo:</p></body></html>',
            )
        )
        self.groupBox_2.setTitle(_translate("MainWindow", "Exportar"))
        self.label.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-size:12pt;">Nome da Formação:</span></p></body></html>',
            )
        )
        self.exportDataButton.setToolTip(
            _translate("MainWindow", "Exportar o dado de TOMI Index")
        )
        self.exportDataButton.setStatusTip(
            _translate(
                "MainWindow",
                "Exportar o dado de TOMI Index. Lembre-se que o dado vai ser exportado utilizando '.' ao invés de ',' para delimitar o decimal.",
            )
        )
        self.exportDataButton.setText(_translate("MainWindow", "Exportar Dados"))
        self.saveButton.setText(_translate("MainWindow", "Salvar Imagem"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Importação")
        )
        self.label_10.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">Modelo de Interpolação:</p></body></html>',
            )
        )
        self.label_8.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">Título do plot:</p></body></html>',
            )
        )
        self.label_9.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">Cor da linha:</p></body></html>',
            )
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Config. plot")
        )
        self.actionSidebar.setText(_translate("MainWindow", "Sidebar"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))
